### ISSUE TITLE
TODO-List before merging hackathon2021 into master

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/Incompact3d#31]
List of updates / fix needed

- [ ] Shall we read statistics when doing a restart ?
- [x] Avoid storing too many restart / statistics file
- [x] DONE. Check the new visualization files (vort/critq) should be written in /data and with the same format for consistency
- [x] TBL broken with scalars

**Comment by mathrack** [comment]
Regarding the check associated with the new visualization files, currently, the vort and critq files should be consistent with the other snapshots (rho / ux / uy / uz / p / phi). The flag [filenamedigits in visu.f90](https://github.com/xcompact3d/Incompact3d/blob/hackathon2021/src/visu.f90#L39) controls the format.

Files should be stored in the folder `data`, see https://github.com/xcompact3d/Incompact3d/blob/hackathon2021/src/visu.f90#L507

This does not apply to TBL because TBL can not call the subroutine `write_field`.

**Comment by slaizet** [comment]
can you remind me why the TBL cannot call `write_field` ?

**Comment by mathrack** [comment]
TBL must be compiled before navier. Visu relies on rescale_pressure and must be compiled after tools. TBL is compiled very early and visu is not yet available at that time. Therefore, TBL can not use `write_field`.
